apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-nginx-deploy
    namespace: webapp
    labels:
        app: nginx
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: test-nginx
              image: nginx:alpine
              ports:
              - containerPort: 80
